spring: 
  prefiles: 
  active: 
  - dev
---
spring: 
  prefiles: dev #
  application:
    name: microservicecloud-config-atguigu-dev
---
spring: 
  prefiles: test #Ի
  application:
    name: microservicecloud-config-atguigu-test
    